@startuml
scale 2
title "Brief Screen Diagram"
class Screen <<abstract>>{
    .. Instance Methods ..
    + __init__(screen: pygame.Surface): None
    + draw_screen(): None
    + adjust_to_screen(): None
    + main_loop(): None
    + resize_screen_variables(): None
}

class MainMenu implements Screen{
    .. Instance Methods ..
    + __init__(screen: pygame.Surface): None
    + draw_screen(): None
    + adjust_to_screen(): None
}

class InfoScreen implements Screen{
    .. Instance Methods ..
    + __init__(): None
    + draw_screen(): None
    + adjust_to_screen(): None
}

@enduml