@startuml
scale 2
title "Main Menu"
class MainMenu implements Screen{
    .. Instance Variables ..
    - _background_picture: pygame.Surface
    - _scaled_picture: pygame.Surface
    - _play_button: GameButton
    - _info_button: GameButton
    - _quit_button: GameButton
    - _menu_text: GameText
    
    + background_picture: pygame.Surface
    + scaled_picture: pygame.Surface
    + play_button: GameButton
    + info_button: GameButton
    + quit_button: GameButton
    + menu_text: GameText

    .. Class Variables .. 
    - X_FACTOR: float
    - FACTOR_FOR_MAIN_TEXT_SIZE: float
    - Y_FACTOR_MENU_TEXT: float
    - Y_FACTOR_PLAY_BUTTON: float
    - Y_FACTOR_OPTIONS_BUTTON: float
    - Y_FACTOR_QUIT_BUTTON: float
    - BACKGROUND_PICTURE_DIRECTORY: str
    .. Instance Methods ..
    + __init__(screen: pygame.Surface): None
    + draw_screen(): None
    + adjust_to_screen(): None
}

@enduml