@startuml
scale 2
title "Main Menu Class Diagram"
class MainMenu implements Screen{
    ..Instance Variables..
    - background_picture: pygame.Surface
    - text: GameText
    - buttons: GameButtons
    ..Overridden Methods..
    + adjust_to_screen(): None
    + draw_screen(): None
}
@enduml