@startuml
scale 2
title "Screens Inheritance Diagram"
    class Screen  <<abstract>>{
    ..Instance Variables..
    - _screen: pygame.Surface
    ..Instance Methods..
    + main_loop(): None
    + resize_screen_variables(): None
    ..Abstract Methods..
    {abstract} + draw_screen(): None
    {abstract} + adjust_to_screen(): None
}

class MainMenu implements Screen{
    ..Instance Variables..
    - background_picture: pygame.Surface
    - text: GameText
    - buttons: GameButtons
    ..Overridden Methods..
    + adjust_to_screen(): None
    + draw_screen(): None
}

class InfoScreen implements Screen{
    ..Instance Variables..
    - _text: GameText
    - button: GameButton
    ..Overridden Methods..
    + adjust_to_screen(): None
    + draw_screen(): None
}

@enduml
