@startuml Physical View
title  Physical View
actor "Player" as P

node "Local PC" {
    node "Docker Container" {
        artifact "Game Engine" as GE
        artifact "GUI" as GUI
        artifact "Maze/Puzzle Info" as MP
    }
}

P --> GUI : Interacts with
GUI --> GE : Sends input to Game Engine
GE --> GUI : Provides updated game state
GUI --> P: Displays current game state
MP --> GE: Provides information about layout/logic
@enduml