@startuml Scenarios
title Scenarios
actor Player

usecase "starting position" as Start
usecase "Move through maze" as Move
usecase "Encounter a puzzle" as EncounterPuzzle
usecase "Solve puzzle(s)" as SolvePuzzle
usecase "Fail puzzle and retry" as FailPuzzle
usecase "Advance to next level" as AdvanceLevel
usecase "Death"

Player --> Start : "Begin Level"
Start --> Move
Move --> EncounterPuzzle
Move --> Death
Death --> Start : "Restart Level"
EncounterPuzzle --> SolvePuzzle : "Correct solution"
SolvePuzzle --> AdvanceLevel : "Success"
EncounterPuzzle --> FailPuzzle : "Wrong answer"
FailPuzzle --> EncounterPuzzle : "Retry"

@endum