@startuml
title "Class Diagrams for Contexts in Interactive UI Elements Module"
class InteractiveDrawable <<abstract>>{
    ..Instance Variables..
    - _state : State
    + state() : State
    + state(state : State) : void
    + draw() : void
    + handle_event(event : Events) : void
    + handle_mouse_position() : void
}

class InteractiveText implements InteractiveDrawable{
    ..Instance Methods..
    - _text : Text
    - _hover_color : str
    - _color : str
    - _outline : Outline
    + text : Text
    + outline : Outline
    + hover_color : str
    + color : str
    ..Overridden Methods..
    + draw() : void
    + handle_mouse_position() : void
}

class InteractiveButton implements InteractiveDrawable{
    ..Instance Methods..
    - _button : Button
    + button : Button
    ..Overridden Methods..
    + handle_mouse_position() : void
}
@enduml