@startuml
scale 2
title "Diagrams For Classes in Game Module"

class TileSet {
    .. Instance Variables ..
    + tiles: List[str]
    + images: Dict[str, pygame.Surface]

    .. Instance Methods ..
    - _load_images(): Dict[str, pygame.Surface]
    - load_or_color(name: str, fallback_color: str): pygame.Surface 
    + get_image(): pygame.Surface 
    + get_tile_name(): str
}

class Game {
    .. Instance Variables ..
    - screen: pygame.Surface
    - clock: pygame.time.Clock
    - tileset: TileSet
    - levels: List[List[int]]
    - level_index: int
    - doors: List[Door]
    - door_unlock_time: None | int

    .. Instance Methods ..
    + load_levels(): List[List[int]]
    + load_level(index: int): None
    + draw(): None
    + update(): None
    + run(): None
    + single_iteration(): None

    .. Static Methods ..
    + game_loop(): None
}

Game *-- TileSet : has

@enduml
