@startuml
scale 2
title "UI Elements Diagram"
class Drawable <<abstract>>{
    .. Instance Variables ..
    - _screen: pygame.Surface
    + screen: pygame.Surface
    .. Abstract Methods..
    {abstract} + draw(): None
    {abstract}+ dynamically_draw(): None
    {abstract}- _adjust_to_changes_(): None
}

class Text implements Drawable{
    .. Instance Variables ..
    ..Overridden Methods..
    + draw(): void
    + dynamically_draw(): None
    - adjust_to_changes(): None
}

@enduml