@startuml
scale 2
title "UI Element Decorators Diagram"


class DrawableDecorator implements Drawable{
    .. Instance Variables ..
    - _drawable: Drawable
    + drawable: Drawable
    ..Overridden Methods..
    + draw(): None
    + dynamically_draw(): None
    - adjust_to_changes(): None
}

class Outline extends DrawableDecorator{
    .. Instance Variables ..
    .. Overridden Methods..
    + draw(): void
    + dynamically_draw(): None
    - adjust_to_changes(): None

}

class Button extends DrawableDecorator{
    .. Instance Variables ..
    .. Overridden Methods..
    + draw(): void
    + dynamically_draw(): None
    - adjust_to_changes(): None

}

@enduml