@startuml
scale 2
title "UI Elements Diagram"
class Drawable <<abstract>>{
    .. Instance Methods ..
    + __init__( screen: pygame.Surface, factor_of_x_pos: float,
                 factor_of_y_pos: float, image_dir: str,
                 size: float, data: Any): None
    + _draw_(): None
    + _dynamically_draw_(): None
    - __adjust_to_changes_(): None
}

class Text implements Drawable{
    .. Instance Methods ..
    + __init__(self, screen: pygame.Surface, factor_of_x_pos: float,
                 factor_of_y_pos: float, image_dir: str, size: float,
                 text: str, color: str): None
    + draw(): void
    + dynamically_draw(): None
    - adjust_to_changes(): None
}


class DrawableDecorator implements Drawable{
    .. Instance Methods ..
    + __init__(drawable: Drawable): None
    + draw(): void
    + dynamically_draw(): None
    - adjust_to_changes(): None
}

class Outline extends DrawableDecorator{
    .. Instance Methods ..
    +__init__(self, drawable: Text, outline_color: str,
                 outline_size: float)
    + draw(): void
    + dynamically_draw(): None
    - adjust_to_changes(): None

}

class Button extends DrawableDecorator{
    .. Instance Methods ..
    + __init__(self, drawable: Drawable, image_dir: str)
    + draw(): void
    + dynamically_draw(): None
    - adjust_to_changes(): None
}
@enduml